#!/usr/bin/env bash

# Only run formatter when there are changes in the client
result=$(git status |awk '/modified:   client\/|new file   client\// { contains = 1 } END { if (contains) print "contains" }')
if [ "$result" = "contains" ]; then
    cd client
    npm run lint:prettier
fi
