// This file is Free Software under the Apache-2.0 License
// without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
//
// SPDX-License-Identifier: Apache-2.0
//
// SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
//  Software-Engineering: 2026 Intevation GmbH <https://intevation.de>

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Contains the URL of the CSAF JSON schema which the document promises to be valid for.
 */
export type JSONSchema = "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/csaf.json";
/**
 * Contains a list of acknowledgment elements associated with the whole document.
 *
 * @minItems 1
 */
export type DocumentAcknowledgments = [Acknowledgment, ...Acknowledgment[]];
/**
 * Contains the names of contributors being recognized.
 *
 * @minItems 1
 */
export type ListOfAcknowledgedNames = [NameOfTheContributor, ...NameOfTheContributor[]];
/**
 * Contains the name of a single contributor being recognized.
 */
export type NameOfTheContributor = string;
/**
 * Contains the name of a contributing organization being recognized.
 */
export type ContributingOrganization = string;
/**
 * SHOULD represent any contextual details the document producers wish to make known about the acknowledgment or acknowledged parties.
 */
export type SummaryOfTheAcknowledgment = string;
/**
 * Specifies a list of URLs or location of the reference to be acknowledged.
 *
 * @minItems 1
 */
export type ListOfURLs = [URLOfAcknowledgment, ...URLOfAcknowledgment[]];
/**
 * Contains the URL or location of the reference to be acknowledged.
 */
export type URLOfAcknowledgment = string;
/**
 * Points to the namespace so referenced.
 */
export type NamespaceOfAggregateSeverity = string;
/**
 * Provides a severity which is independent of - and in addition to - any other standard metric for determining the impact or severity of a given vulnerability (such as CVSS).
 */
export type TextOfAggregateSeverity = string;
/**
 * Defines a short canonical name, chosen by the document producer, which will inform the end user as to the category of document.
 */
export type DocumentCategory = string;
/**
 * Gives the version of the CSAF specification which the document was generated for.
 */
export type CSAFVersion = "2.1";
/**
 * Provides the unique ID for the sharing group.
 */
export type SharingGroupID = string;
/**
 * Contains a human-readable name for the sharing group.
 */
export type SharingGroupName = string;
/**
 * Provides a textual description of additional constraints.
 */
export type TextualDescription = string;
/**
 * Provides the TLP label of the document.
 */
export type LabelOfTLP = "AMBER" | "AMBER+STRICT" | "CLEAR" | "GREEN" | "RED";
/**
 * Provides a URL where to find the textual description of the TLP version which is used in this document. Default is the URL to the definition by FIRST.
 */
export type URLOfTLPVersion = string;
/**
 * Identifies the language used by this document, corresponding to IETF BCP 47 / RFC 5646.
 */
export type DocumentLanguage = string;
/**
 * Contains the SPDX license expression for the CSAF document.
 */
export type LicenseExpression = string;
/**
 * Holds notes associated with the whole document.
 *
 * @minItems 1
 */
export type DocumentNotes = [Note, ...Note[]];
/**
 * Indicates who is intended to read it.
 */
export type AudienceOfNote = string;
/**
 * Contains the information of what kind of note this is.
 */
export type NoteCategory = "description" | "details" | "faq" | "general" | "legal_disclaimer" | "other" | "summary";
/**
 * Specifies a list of product_group_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductGroupIds = [ReferenceTokenForProductGroupInstance, ...ReferenceTokenForProductGroupInstance[]];
/**
 * Token required to identify a group of products so that it can be referred to from other parts in the document. There is no predefined or required format for the product_group_id as long as it uniquely identifies a group in the context of the current document.
 */
export type ReferenceTokenForProductGroupInstance = string;
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Token required to identify a full_product_name so that it can be referred to from other parts in the document. There is no predefined or required format for the product_id as long as it uniquely identifies a product in the context of the current document.
 */
export type ReferenceTokenForProductInstance = string;
/**
 * Holds the content of the note. Content varies depending on type.
 */
export type NoteContent = string;
/**
 * Provides a concise description of what is contained in the text of the note.
 */
export type TitleOfNote = string;
/**
 * Provides information about the category of publisher releasing the document.
 */
export type CategoryOfPublisher =
  "coordinator" | "discoverer" | "multiplier" | "other" | "translator" | "user" | "vendor";
/**
 * Information on how to contact the publisher, possibly including details such as web sites, email addresses, phone numbers, and postal mail addresses.
 */
export type ContactDetails = string;
/**
 * Provides information about the authority of the issuing party to release the document, in particular, the party's constituency and responsibilities or other obligations.
 */
export type IssuingAuthority = string;
/**
 * Contains the name of the issuing party.
 */
export type NameOfPublisher = string;
/**
 * Contains a URL which is under control of the issuing party and can be used as a globally unique identifier for that issuing party.
 */
export type NamespaceOfPublisher = string;
/**
 * Holds a list of references associated with the whole document.
 *
 * @minItems 1
 */
export type DocumentReferences = [Reference, ...Reference[]];
/**
 * Indicates whether the reference points to the same document or vulnerability in focus (depending on scope) or to an external resource.
 */
export type CategoryOfReference = "external" | "self";
/**
 * Indicates what this reference refers to.
 */
export type SummaryOfTheReference = string;
/**
 * Provides the URL for the reference.
 */
export type URLOfReference = string;
/**
 * If this copy of the document is a translation then the value of this property describes from which language this document was translated.
 */
export type SourceLanguage = string;
/**
 * This SHOULD be a canonical name for the document, and sufficiently unique to distinguish it from similar documents.
 */
export type TitleOfThisDocument = string;
/**
 * Contains a list of alternate names for the same document.
 *
 * @minItems 1
 */
export type Aliases = [AlternateName, ...AlternateName[]];
/**
 * Specifies a non-empty string that represents a distinct optional alternative ID used to refer to the document.
 */
export type AlternateName = string;
/**
 * The date when the current revision of this document was released
 */
export type CurrentReleaseDate = string;
/**
 * This SHOULD be the current date that the document was generated. Because documents are often generated internally by a document producer and exist for a nonzero amount of time before being released, this field MAY be different from the Initial Release Date and Current Release Date.
 */
export type DateOfDocumentGeneration = string;
/**
 * Represents the name of the engine that generated the CSAF document.
 */
export type EngineName = string;
/**
 * Contains the version of the engine that generated the CSAF document.
 */
export type EngineVersion = string;
/**
 * The ID is a simple label that provides for a wide range of numbering values, types, and schemes. Its value SHOULD be assigned and maintained by the original document issuing authority.
 */
export type UniqueIdentifierForTheDocument = string;
/**
 * The date when this document was first released to the specified target group.
 */
export type InitialReleaseDate = string;
/**
 * Holds one revision item for each version of the CSAF document, including the initial one.
 *
 * @minItems 1
 */
export type RevisionHistory = [Revision, ...Revision[]];
/**
 * The date of the revision entry
 */
export type DateOfTheRevision = string;
/**
 * Contains the version string used in an existing document with the same content.
 */
export type LegacyVersionOfTheRevision = string;
/**
 * Specifies a version string to denote clearly the evolution of the content of the document. Format must be either integer or semantic versioning.
 */
export type Version = string;
/**
 * Holds a single non-empty string representing a short description of the changes.
 */
export type SummaryOfTheRevision = string;
/**
 * Defines the draft status of the document.
 */
export type DocumentStatus = "draft" | "final" | "interim";
/**
 * Contains a list of extensions valid at the document property level of the CSAF document and associated with this document metadata.
 *
 * @minItems 1
 */
export type DocumentLevelExtensions = [CSAFExtensionContent, ...CSAFExtensionContent[]];
/**
 * Contains the URL of the CSAF Extension JSON schema which the JSON object promises to be valid for.
 */
export type CSAFExtensionSchema = string;
/**
 * Holds the category of the extension content.
 */
export type ExtensionCategory = "critical" | "high_value" | "informational";
/**
 * Determines whether using the extension would fail a mandatory test.
 */
export type Critical = boolean;
/**
 * Contains branch elements as children of the current element.
 *
 * @minItems 1
 */
export type ListOfBranches = [Branch, ...Branch[]];
/**
 * Describes the characteristics of the labeled branch.
 */
export type CategoryOfTheBranch =
  | "architecture"
  | "host_name"
  | "language"
  | "patch_level"
  | "platform"
  | "product_family"
  | "product_name"
  | "product_version"
  | "product_version_range"
  | "service_pack"
  | "specification"
  | "vendor";
/**
 * Contains the canonical descriptor or 'friendly name' of the branch.
 */
export type NameOfTheBranch = string;
/**
 * The value should be the product’s full canonical name, including version number and other attributes, as it would be used in a human-friendly document.
 */
export type TextualDescriptionOfTheProduct = string;
/**
 * The Common Platform Enumeration (CPE) attribute refers to a method for naming platforms external to this specification.
 */
export type CommonPlatformEnumerationRepresentation = string;
/**
 * Contains a list of cryptographic hashes usable to identify files.
 *
 * @minItems 1
 */
export type ListOfHashes = [CryptographicHashes, ...CryptographicHashes[]];
/**
 * Contains a list of cryptographic hashes for this file.
 *
 * @minItems 1
 */
export type ListOfFileHashes = [FileHash, ...FileHash[]];
/**
 * Contains the name of the cryptographic hash algorithm used to calculate the value.
 */
export type AlgorithmOfTheCryptographicHash = string;
/**
 * Contains the cryptographic hash value in lowercase hexadecimal representation.
 */
export type ValueOfTheCryptographicHash = string;
/**
 * Contains the name of the file which is identified by the hash values.
 */
export type Filename = string;
/**
 * Contains a list of model numbers.
 *
 * @minItems 1
 */
export type ListOfModels = [ModelNumber, ...ModelNumber[]];
/**
 * Contains a model number of the component to identify - possibly with placeholders.
 */
export type ModelNumber = string;
/**
 * Contains a list of Package-URLs (PURL).
 *
 * @minItems 1
 */
export type ListOfPURLs = [PackageURLRepresentation, ...PackageURLRepresentation[]];
/**
 * The Package-URL (PURL) attribute refers to a method for reliably identifying and locating software packages external to this specification.
 */
export type PackageURLRepresentation = string;
/**
 * Contains a list of URLs where SBOMs for this product can be retrieved.
 *
 * @minItems 1
 */
export type ListOfSBOMURLs = [SBOMURL, ...SBOMURL[]];
/**
 * Contains a URL of one SBOM for this product.
 */
export type SBOMURL = string;
/**
 * Contains a list of serial numbers.
 *
 * @minItems 1
 */
export type ListOfSerialNumbers = [SerialNumber, ...SerialNumber[]];
/**
 * Contains a serial number of the component to identify - possibly with placeholders.
 */
export type SerialNumber = string;
/**
 * Contains a list of stock keeping units.
 *
 * @minItems 1
 */
export type ListOfStockKeepingUnits = [StockKeepingUnit, ...StockKeepingUnit[]];
/**
 * Contains a stock keeping unit (SKU) which is used in the ordering process to identify the component - possibly with placeholders.
 */
export type StockKeepingUnit = string;
/**
 * Contains a list of identifiers which are either vendor-specific or derived from a standard not yet supported.
 *
 * @minItems 1
 */
export type ListOfGenericURIs = [GenericURI, ...GenericURI[]];
/**
 * Refers to a URL which provides the name and knowledge about the specification used or is the namespace in which these values are valid.
 */
export type NamespaceOfTheGenericURI = string;
/**
 * Contains the identifier itself.
 */
export type URI = string;
/**
 * Contains a list of extensions valid at the full product name element level of the CSAF document and associated with this full product name element.
 *
 * @minItems 1
 */
export type ProductLevelExtensions = [CSAFExtensionContent, ...CSAFExtensionContent[]];
/**
 * Contains a list of full product names.
 *
 * @minItems 1
 */
export type ListOfFullProductNames = [FullProductName, ...FullProductName[]];
/**
 * Contains a list of product groups.
 *
 * @minItems 1
 */
export type ListOfProductGroups = [ProductGroup, ...ProductGroup[]];
/**
 * Lists the product_ids of those products which known as one group in the document.
 *
 * @minItems 2
 */
export type ListOfProductIDs = [
  ReferenceTokenForProductInstance,
  ReferenceTokenForProductInstance,
  ...ReferenceTokenForProductInstance[]
];
/**
 * Gives a short, optional description of the group.
 */
export type SummaryOfTheProductGroup = string;
/**
 * Contains a list of product paths.
 *
 * @minItems 1
 */
export type ListOfProductPaths = [ProductPath, ...ProductPath[]];
/**
 * Token required to identify a full_product_name so that it can be referred to from other parts in the document. There is no predefined or required format for the product_id as long as it uniquely identifies a product in the context of the current document.
 */
export type ReferenceTokenForProductInstance1 = string;
/**
 * Contains an ordered list of product subpaths, each one relating to the path defined by all previous elements up to the beginning node of the product path.
 *
 * @minItems 1
 */
export type ListOfProductSubpaths = [Subpath, ...Subpath[]];
/**
 * Defines the category of relationship between the previous item and the referenced next product.
 */
export type RelationshipCategory =
  "default_component_of" | "external_component_of" | "installed_on" | "installed_with" | "optional_component_of";
/**
 * Token required to identify a full_product_name so that it can be referred to from other parts in the document. There is no predefined or required format for the product_id as long as it uniquely identifies a product in the context of the current document.
 */
export type ReferenceTokenForProductInstance2 = string;
/**
 * Represents a list of all relevant vulnerability information items.
 *
 * @minItems 1
 */
export type Vulnerabilities = [Vulnerability, ...Vulnerability[]];
/**
 * Contains a list of acknowledgment elements associated with this vulnerability item.
 *
 * @minItems 1
 */
export type VulnerabilityAcknowledgments = [Acknowledgment, ...Acknowledgment[]];
/**
 * Holds the MITRE standard Common Vulnerabilities and Exposures (CVE) tracking number for the vulnerability.
 */
export type CVE = string;
/**
 * Contains a list of CWEs.
 *
 * @minItems 1
 */
export type ListOfCWEs = [CWE, ...CWE[]];
/**
 * Holds the ID for the weakness associated.
 */
export type WeaknessID = string;
/**
 * Holds the full name of the weakness as given in the CWE specification.
 */
export type WeaknessName = string;
/**
 * Holds the version string of the CWE specification this weakness was extracted from.
 */
export type CWEVersion = string;
/**
 * Holds the date and time the vulnerability was originally disclosed to the public.
 */
export type DisclosureDate = string;
/**
 * Holds the date and time the vulnerability was originally discovered.
 */
export type DiscoveryDate = string;
/**
 * Contains a list of dates of first known exploitations.
 *
 * @minItems 1
 */
export type ListOfFirstKnownExploitationDates = [FirstKnownExploitationDate, ...FirstKnownExploitationDate[]];
/**
 * Contains the date when the information was last updated.
 */
export type DateOfTheInformation = string;
/**
 * Contains the date when the exploitation happened.
 */
export type DateOfTheExploitation = string;
/**
 * Contains a list of machine readable flags.
 *
 * @minItems 1
 */
export type ListOfFlags = [Flag, ...Flag[]];
/**
 * Contains the date when assessment was done or the flag was assigned.
 */
export type DateOfTheFlag = string;
/**
 * Specifies the machine readable label.
 */
export type LabelOfTheFlag =
  | "component_not_present"
  | "inline_mitigations_already_exist"
  | "vulnerable_code_cannot_be_controlled_by_adversary"
  | "vulnerable_code_not_in_execute_path"
  | "vulnerable_code_not_present";
/**
 * Represents a list of unique labels or tracking IDs for the vulnerability (if such information exists).
 *
 * @minItems 1
 */
export type ListOfIDs = [ID, ...ID[]];
/**
 * Indicates the name of the vulnerability tracking or numbering system.
 */
export type SystemName = string;
/**
 * Is unique label or tracking ID for the vulnerability (if such information exists).
 */
export type Text = string;
/**
 * Contains a list of involvements.
 *
 * @minItems 1
 */
export type ListOfInvolvements = [Involvement, ...Involvement[]];
/**
 * Contains the contact information of the party that was used in this state.
 */
export type PartyContactInformation = string;
/**
 * Holds the date and time of the involvement entry.
 */
export type DateOfInvolvement = string;
/**
 * Defines the category of the involved party.
 */
export type PartyCategory = "coordinator" | "discoverer" | "other" | "user" | "vendor";
/**
 * Defines contact status of the involved party.
 */
export type PartyStatus = "completed" | "contact_attempted" | "disputed" | "in_progress" | "not_contacted" | "open";
/**
 * Contains additional context regarding what is going on.
 */
export type SummaryOfTheInvolvement = string;
/**
 * Contains metric objects for the current vulnerability.
 *
 * @minItems 1
 */
export type ListOfMetrics = [Metric, ...Metric[]];
export type CVSSv3 =
  JSONSchemaForCommonVulnerabilityScoringSystemVersion30 | JSONSchemaForCommonVulnerabilityScoringSystemVersion31;
export type CVSSv4 = (
  | {
      baseScore?: number;
      baseSeverity?: "NONE";
      [k: string]: unknown;
    }
  | {
      baseScore?: number;
      baseSeverity?: "LOW";
      [k: string]: unknown;
    }
  | {
      baseScore?: number;
      baseSeverity?: "MEDIUM";
      [k: string]: unknown;
    }
  | {
      baseScore?: number;
      baseSeverity?: "HIGH";
      [k: string]: unknown;
    }
  | {
      baseScore?: number;
      baseSeverity?: "CRITICAL";
      [k: string]: unknown;
    }
) & {
  Automatable?: "NO" | "YES" | "NOT_DEFINED";
  Recovery?: "AUTOMATIC" | "USER" | "IRRECOVERABLE" | "NOT_DEFINED";
  Safety?: "NEGLIGIBLE" | "PRESENT" | "NOT_DEFINED";
  attackComplexity?: "HIGH" | "LOW";
  attackRequirements?: "NONE" | "PRESENT";
  attackVector?: "NETWORK" | "ADJACENT" | "LOCAL" | "PHYSICAL";
  availabilityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  confidentialityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  exploitMaturity?: "UNREPORTED" | "PROOF_OF_CONCEPT" | "ATTACKED" | "NOT_DEFINED";
  integrityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  modifiedAttackComplexity?: "HIGH" | "LOW" | "NOT_DEFINED";
  modifiedAttackRequirements?: "NONE" | "PRESENT" | "NOT_DEFINED";
  modifiedAttackVector?: "NETWORK" | "ADJACENT" | "LOCAL" | "PHYSICAL" | "NOT_DEFINED";
  modifiedPrivilegesRequired?: "HIGH" | "LOW" | "NONE" | "NOT_DEFINED";
  modifiedSubAvailabilityImpact?: "NEGLIGIBLE" | "LOW" | "HIGH" | "SAFETY" | "NOT_DEFINED";
  modifiedSubConfidentialityImpact?: "NEGLIGIBLE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedSubIntegrityImpact?: "NEGLIGIBLE" | "LOW" | "HIGH" | "SAFETY" | "NOT_DEFINED";
  modifiedUserInteraction?: "NONE" | "PASSIVE" | "ACTIVE" | "NOT_DEFINED";
  modifiedVulnAvailabilityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedVulnConfidentialityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedVulnIntegrityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  privilegesRequired?: "HIGH" | "LOW" | "NONE";
  providerUrgency?: "CLEAR" | "GREEN" | "AMBER" | "RED" | "NOT_DEFINED";
  subAvailabilityImpact?: "NONE" | "LOW" | "HIGH";
  subConfidentialityImpact?: "NONE" | "LOW" | "HIGH";
  subIntegrityImpact?: "NONE" | "LOW" | "HIGH";
  userInteraction?: "NONE" | "PASSIVE" | "ACTIVE";
  valueDensity?: "DIFFUSE" | "CONCENTRATED" | "NOT_DEFINED";
  vectorString: string;
  /**
   * CVSS Version
   */
  version: "4.0";
  vulnAvailabilityImpact?: "NONE" | "LOW" | "HIGH";
  vulnConfidentialityImpact?: "NONE" | "LOW" | "HIGH";
  vulnIntegrityImpact?: "NONE" | "LOW" | "HIGH";
  vulnerabilityResponseEffort?: "LOW" | "MODERATE" | "HIGH" | "NOT_DEFINED";
  [k: string]: unknown;
};
/**
 * Contains the rank ordering of probabilities from highest to lowest.
 */
export type Percentile = string;
/**
 * Contains the likelihood that any exploitation activity for this Vulnerability is being observed in the 30 days following the given timestamp.
 */
export type Probability = string;
/**
 * Holds the date and time the EPSS value was recorded.
 */
export type EPSSTimestamp = string;
/**
 * Contains an assessment of the severity of the vulnerability regarding the products on a qualitative scale.
 */
export type QualitativeSeverityRating = "critical" | "high" | "low" | "medium" | "none";
/**
 * Timestamp of the selections, in RFC 3339 format.
 */
export type Timestamp = string;
/**
 * The schema version of this selection list.
 */
export type Schemaversion = "2.0.0";
/**
 * Optional list of identifiers for the item or items (vulnerabilities, reports, advisories, systems, assets, etc.) being evaluated by these selections.
 *
 * @minItems 1
 */
export type TargetIds = [string, ...string[]];
/**
 * List of selections made from decision points. Each selection item corresponds to value keys contained in a specific decision point identified by its namespace, key, and version. Note that selection objects are deliberately minimal objects and do not contain the full decision point details.
 *
 * @minItems 1
 */
export type Selections = [Selection, ...Selection[]];
/**
 * The namespace of the SSVC object.
 */
export type Namespace = string;
/**
 * A short, non-empty string identifier for the object. Keys must start with an alphanumeric, contain only alphanumerics and `_`, and end with an alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should not be used for new objects.)
 */
export type Key = string;
/**
 * The version of the SSVC object. This must be a valid semantic version string.
 */
export type Version1 = string;
export type Name = string;
export type Definition = string;
/**
 * A list of selected value keys from the decision point values.
 *
 * @minItems 1
 */
export type Values = [MinimalDecisionPointValue, ...MinimalDecisionPointValue[]];
export type Name1 = string;
export type Definition1 = string;
/**
 * A short, non-empty string identifier for the object. Keys must start with an alphanumeric, contain only alphanumerics and `_`, and end with an alphanumeric.(`T*` is explicitly grandfathered in as a valid key, but should not be used for new objects.)
 */
export type Key1 = string;
/**
 * A list of resources that provide additional context about the decision points found in this selection.
 *
 * @minItems 1
 */
export type DecisionPointResources = [Reference1, ...Reference1[]];
export type Uri = string;
export type Summary = string;
/**
 * A list of references that provide additional context about the specific values selected.
 *
 * @minItems 1
 */
export type References = [Reference1, ...Reference1[]];
/**
 * Contains a list of extensions valid at the metrics-content-level of the CSAF document and associated with this metric element.
 *
 * @minItems 1
 */
export type MetricsContentLevelExtensions = [CSAFExtensionContent, ...CSAFExtensionContent[]];
/**
 * Contains the URL of the source that originally determined the metric.
 */
export type Source = string;
/**
 * Holds notes associated with this vulnerability item.
 *
 * @minItems 1
 */
export type VulnerabilityNotes = [Note, ...Note[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds1 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds2 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds3 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds4 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds5 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds6 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds7 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds8 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Specifies a list of product_ids to give context to the parent item.
 *
 * @minItems 1
 */
export type ListOfProductIds9 = [ReferenceTokenForProductInstance, ...ReferenceTokenForProductInstance[]];
/**
 * Holds a list of references associated with this vulnerability item.
 *
 * @minItems 1
 */
export type VulnerabilityReferences = [Reference, ...Reference[]];
/**
 * Contains a list of remediations.
 *
 * @minItems 1
 */
export type ListOfRemediations = [Remediation, ...Remediation[]];
/**
 * Specifies the category which this remediation belongs to.
 */
export type CategoryOfTheRemediation =
  "fix_planned" | "mitigation" | "no_fix_planned" | "none_available" | "optional_patch" | "vendor_fix" | "workaround";
/**
 * Contains the date from which the remediation is available.
 */
export type DateOfTheRemediation = string;
/**
 * Contains a thorough human-readable discussion of the remediation.
 */
export type DetailsOfTheRemediation = string;
/**
 * Contains a list of entitlements.
 *
 * @minItems 1
 */
export type ListOfEntitlements = [EntitlementOfTheRemediation, ...EntitlementOfTheRemediation[]];
/**
 * Contains any possible vendor-defined constraints for obtaining fixed software or hardware that fully resolves the vulnerability.
 */
export type EntitlementOfTheRemediation = string;
/**
 * Specifies what category of restart is required by this remediation to become effective.
 */
export type CategoryOfRestart =
  "connected" | "dependencies" | "machine" | "none" | "parent" | "service" | "system" | "vulnerable_component" | "zone";
/**
 * Provides additional information for the restart. This can include details on procedures, scope or impact.
 */
export type AdditionalRestartInformation = string;
/**
 * Contains the URL where to obtain the remediation.
 */
export type URLToTheRemediation = string;
/**
 * Contains information about a vulnerability that can change with time.
 *
 * @minItems 1
 */
export type ListOfThreats = [Threat, ...Threat[]];
/**
 * Categorizes the threat according to the rules of the specification.
 */
export type CategoryOfTheThreat = "exploit_status" | "impact" | "target_set";
/**
 * Contains the date when the assessment was done or the threat appeared.
 */
export type DateOfTheThreat = string;
/**
 * Represents a thorough human-readable discussion of the threat.
 */
export type DetailsOfTheThreat = string;
/**
 * Gives the document producer the ability to apply a canonical name or title to the vulnerability.
 */
export type Title = string;
/**
 * Contains a list of extensions valid at the vulnerability item level of the CSAF document and associated with this vulnerability element.
 *
 * @minItems 1
 */
export type VulnerabilityLevelExtensions = [CSAFExtensionContent, ...CSAFExtensionContent[]];
/**
 * Contains a list of extensions valid at the root-level of the CSAF document and associated with this CSAF document.
 *
 * @minItems 1
 */
export type RootLevelExtensions = [CSAFExtensionContent, ...CSAFExtensionContent[]];

/**
 * Representation of security advisory information as a JSON document.
 */
export interface CSAFDocumentv2_1 {
  $schema: JSONSchema;
  document: DocumentLevelMetaData;
  product_tree?: ProductTree;
  vulnerabilities?: Vulnerabilities;
  x_extensions?: RootLevelExtensions;
}
/**
 * Captures the meta-data about this document describing a particular set of security advisories.
 */
export interface DocumentLevelMetaData {
  acknowledgments?: DocumentAcknowledgments;
  aggregate_severity?: AggregateSeverity;
  category: DocumentCategory;
  csaf_version: CSAFVersion;
  distribution: RulesForDocumentSharing;
  lang?: DocumentLanguage;
  license_expression?: LicenseExpression;
  notes?: DocumentNotes;
  publisher: Publisher;
  references?: DocumentReferences;
  source_lang?: SourceLanguage;
  title: TitleOfThisDocument;
  tracking: Tracking;
  x_extensions?: DocumentLevelExtensions;
}
/**
 * Acknowledges contributions by describing those that contributed.
 */
export interface Acknowledgment {
  names?: ListOfAcknowledgedNames;
  organization?: ContributingOrganization;
  summary?: SummaryOfTheAcknowledgment;
  urls?: ListOfURLs;
}
/**
 * Is a vehicle that is provided by the document producer to convey the urgency and criticality with which the one or more vulnerabilities reported should be addressed. It is a document-level metric and applied to the document as a whole — not any specific vulnerability. The range of values in this field is defined according to the document producer's policies and procedures.
 */
export interface AggregateSeverity {
  namespace?: NamespaceOfAggregateSeverity;
  text: TextOfAggregateSeverity;
}
/**
 * Describe any constraints on how this document might be shared.
 */
export interface RulesForDocumentSharing {
  sharing_group?: SharingGroup;
  text?: TextualDescription;
  tlp: TrafficLightProtocolTLP;
}
/**
 * Contains information about the group this document is intended to be shared with.
 */
export interface SharingGroup {
  id: SharingGroupID;
  name?: SharingGroupName;
}
/**
 * Provides details about the TLP classification of the document.
 */
export interface TrafficLightProtocolTLP {
  label: LabelOfTLP;
  url?: URLOfTLPVersion;
}
/**
 * Is a place to put all manner of text blobs related to the current context.
 */
export interface Note {
  audience?: AudienceOfNote;
  category: NoteCategory;
  group_ids?: ListOfProductGroupIds;
  product_ids?: ListOfProductIds;
  text: NoteContent;
  title?: TitleOfNote;
}
/**
 * Provides information about the publisher of the document.
 */
export interface Publisher {
  category: CategoryOfPublisher;
  contact_details?: ContactDetails;
  issuing_authority?: IssuingAuthority;
  name: NameOfPublisher;
  namespace: NamespaceOfPublisher;
}
/**
 * Holds any reference to conferences, papers, advisories, and other resources that are related and considered related to either a surrounding part of or the entire document and to be of value to the document consumer.
 */
export interface Reference {
  category?: CategoryOfReference;
  summary: SummaryOfTheReference;
  url: URLOfReference;
}
/**
 * Is a container designated to hold all management attributes necessary to track a CSAF document as a whole.
 */
export interface Tracking {
  aliases?: Aliases;
  current_release_date: CurrentReleaseDate;
  generator?: DocumentGenerator;
  id: UniqueIdentifierForTheDocument;
  initial_release_date: InitialReleaseDate;
  revision_history: RevisionHistory;
  status: DocumentStatus;
  version: Version;
}
/**
 * Is a container to hold all elements related to the generation of the document. These items will reference when the document was actually created, including the date it was generated and the entity that generated it.
 */
export interface DocumentGenerator {
  date?: DateOfDocumentGeneration;
  engine: EngineOfDocumentGeneration;
}
/**
 * Contains information about the engine that generated the CSAF document.
 */
export interface EngineOfDocumentGeneration {
  name: EngineName;
  version?: EngineVersion;
}
/**
 * Contains all the information elements required to track the evolution of a CSAF document.
 */
export interface Revision {
  date: DateOfTheRevision;
  legacy_version?: LegacyVersionOfTheRevision;
  number: Version;
  summary: SummaryOfTheRevision;
}
/**
 * Representation of additional information extending a CSAF Document.
 */
export interface CSAFExtensionContent {
  $schema: CSAFExtensionSchema;
  category: ExtensionCategory;
  content: Content;
  critical: Critical;
}
/**
 * Contains the additional information in its properties.
 */
export interface Content {
  [k: string]: unknown;
}
/**
 * Is a container for all fully qualified product names that can be referenced elsewhere in the document.
 */
export interface ProductTree {
  branches?: ListOfBranches;
  full_product_names?: ListOfFullProductNames;
  product_groups?: ListOfProductGroups;
  product_paths?: ListOfProductPaths;
}
/**
 * Is a part of the hierarchical structure of the product tree.
 */
export interface Branch {
  branches?: ListOfBranches;
  category: CategoryOfTheBranch;
  name: NameOfTheBranch;
  product?: FullProductName;
}
/**
 * Specifies information about the product and assigns the product_id.
 */
export interface FullProductName {
  name: TextualDescriptionOfTheProduct;
  product_id: ReferenceTokenForProductInstance;
  product_identification_helper?: HelperToIdentifyTheProduct;
  x_extensions?: ProductLevelExtensions;
}
/**
 * Provides at least one method which aids in identifying the product in an asset database.
 */
export interface HelperToIdentifyTheProduct {
  cpe?: CommonPlatformEnumerationRepresentation;
  hashes?: ListOfHashes;
  model_numbers?: ListOfModels;
  purls?: ListOfPURLs;
  sbom_urls?: ListOfSBOMURLs;
  serial_numbers?: ListOfSerialNumbers;
  skus?: ListOfStockKeepingUnits;
  x_generic_uris?: ListOfGenericURIs;
}
/**
 * Contains all information to identify a file based on its cryptographic hash values.
 */
export interface CryptographicHashes {
  file_hashes: ListOfFileHashes;
  filename: Filename;
}
/**
 * Contains one hash value and algorithm of the file to be identified.
 */
export interface FileHash {
  algorithm: AlgorithmOfTheCryptographicHash;
  value: ValueOfTheCryptographicHash;
}
/**
 * Provides a generic extension point for any identifier which is either vendor-specific or derived from a standard not yet supported.
 */
export interface GenericURI {
  namespace: NamespaceOfTheGenericURI;
  uri: URI;
}
/**
 * Defines a new logical group of products that can then be referred to in other parts of the document to address a group of products with a single identifier.
 */
export interface ProductGroup {
  group_id: ReferenceTokenForProductGroupInstance;
  product_ids: ListOfProductIDs;
  summary?: SummaryOfTheProductGroup;
}
/**
 * Establishes a path along existing full_product_name_t elements, allowing the document producer to define a path of multiple products that form a new full_product_name entry.
 */
export interface ProductPath {
  beginning_product_reference: ReferenceTokenForProductInstance1;
  full_product_name: FullProductName;
  subpaths: ListOfProductSubpaths;
}
/**
 * Contains the next node along the current path and its relationship to the previous node.
 */
export interface Subpath {
  category: RelationshipCategory;
  next_product_reference: ReferenceTokenForProductInstance2;
}
/**
 * Is a container for the aggregation of all fields that are related to a single vulnerability in the document.
 */
export interface Vulnerability {
  acknowledgments?: VulnerabilityAcknowledgments;
  cve?: CVE;
  cwes?: ListOfCWEs;
  disclosure_date?: DisclosureDate;
  discovery_date?: DiscoveryDate;
  first_known_exploitation_dates?: ListOfFirstKnownExploitationDates;
  flags?: ListOfFlags;
  ids?: ListOfIDs;
  involvements?: ListOfInvolvements;
  metrics?: ListOfMetrics;
  notes?: VulnerabilityNotes;
  product_status?: ProductStatus;
  references?: VulnerabilityReferences;
  remediations?: ListOfRemediations;
  threats?: ListOfThreats;
  title?: Title;
  x_extensions?: VulnerabilityLevelExtensions;
}
/**
 * Holds the MITRE standard Common Weakness Enumeration (CWE) for the weakness associated.
 */
export interface CWE {
  id: WeaknessID;
  name: WeaknessName;
  version: CWEVersion;
}
/**
 * Contains information on when this vulnerability was first known to be exploited in the wild in the products specified.
 */
export interface FirstKnownExploitationDate {
  date: DateOfTheInformation;
  exploitation_date: DateOfTheExploitation;
  group_ids?: ListOfProductGroupIds;
  product_ids?: ListOfProductIds;
}
/**
 * Contains product specific information in regard to this vulnerability as a single machine readable flag.
 */
export interface Flag {
  date?: DateOfTheFlag;
  group_ids?: ListOfProductGroupIds;
  label: LabelOfTheFlag;
  product_ids?: ListOfProductIds;
}
/**
 * Contains a single unique label or tracking ID for the vulnerability.
 */
export interface ID {
  system_name: SystemName;
  text: Text;
}
/**
 * Is a container, that allows the document producers to comment on the level of involvement (or engagement) of themselves or third parties in the vulnerability identification, scoping, and remediation process.
 */
export interface Involvement {
  contact?: PartyContactInformation;
  date?: DateOfInvolvement;
  group_ids?: ListOfProductGroupIds;
  party: PartyCategory;
  product_ids?: ListOfProductIds;
  status: PartyStatus;
  summary?: SummaryOfTheInvolvement;
}
/**
 * Contains all metadata about the metric including products it applies to and the source and the content itself.
 */
export interface Metric {
  content: Content1;
  products: ListOfProductIds;
  source?: Source;
}
/**
 * Specifies information about (at least one) metric or score for the given products regarding the current vulnerability.
 */
export interface Content1 {
  cvss_v2?: CVSSv2;
  cvss_v3?: CVSSv3;
  cvss_v4?: CVSSv4;
  epss?: EPSS;
  qualitative_severity_rating?: QualitativeSeverityRating;
  ssvc_v2?: SSVCv2;
  x_extensions?: MetricsContentLevelExtensions;
}
export interface CVSSv2 {
  /**
   * CVSS Version
   */
  version: "2.0";
  vectorString: string;
  accessVector?: "NETWORK" | "ADJACENT_NETWORK" | "LOCAL";
  accessComplexity?: "HIGH" | "MEDIUM" | "LOW";
  authentication?: "MULTIPLE" | "SINGLE" | "NONE";
  confidentialityImpact?: "NONE" | "PARTIAL" | "COMPLETE";
  integrityImpact?: "NONE" | "PARTIAL" | "COMPLETE";
  availabilityImpact?: "NONE" | "PARTIAL" | "COMPLETE";
  baseScore: number;
  exploitability?: "UNPROVEN" | "PROOF_OF_CONCEPT" | "FUNCTIONAL" | "HIGH" | "NOT_DEFINED";
  remediationLevel?: "OFFICIAL_FIX" | "TEMPORARY_FIX" | "WORKAROUND" | "UNAVAILABLE" | "NOT_DEFINED";
  reportConfidence?: "UNCONFIRMED" | "UNCORROBORATED" | "CONFIRMED" | "NOT_DEFINED";
  temporalScore?: number;
  collateralDamagePotential?: "NONE" | "LOW" | "LOW_MEDIUM" | "MEDIUM_HIGH" | "HIGH" | "NOT_DEFINED";
  targetDistribution?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  confidentialityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  integrityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  availabilityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  environmentalScore?: number;
  [k: string]: unknown;
}
export interface JSONSchemaForCommonVulnerabilityScoringSystemVersion30 {
  /**
   * CVSS Version
   */
  version: "3.0";
  vectorString: string;
  attackVector?: "NETWORK" | "ADJACENT_NETWORK" | "LOCAL" | "PHYSICAL";
  attackComplexity?: "HIGH" | "LOW";
  privilegesRequired?: "HIGH" | "LOW" | "NONE";
  userInteraction?: "NONE" | "REQUIRED";
  scope?: "UNCHANGED" | "CHANGED";
  confidentialityImpact?: "NONE" | "LOW" | "HIGH";
  integrityImpact?: "NONE" | "LOW" | "HIGH";
  availabilityImpact?: "NONE" | "LOW" | "HIGH";
  baseScore: number;
  baseSeverity: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  exploitCodeMaturity?: "UNPROVEN" | "PROOF_OF_CONCEPT" | "FUNCTIONAL" | "HIGH" | "NOT_DEFINED";
  remediationLevel?: "OFFICIAL_FIX" | "TEMPORARY_FIX" | "WORKAROUND" | "UNAVAILABLE" | "NOT_DEFINED";
  reportConfidence?: "UNKNOWN" | "REASONABLE" | "CONFIRMED" | "NOT_DEFINED";
  temporalScore?: number;
  temporalSeverity?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  confidentialityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  integrityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  availabilityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  modifiedAttackVector?: "NETWORK" | "ADJACENT_NETWORK" | "LOCAL" | "PHYSICAL" | "NOT_DEFINED";
  modifiedAttackComplexity?: "HIGH" | "LOW" | "NOT_DEFINED";
  modifiedPrivilegesRequired?: "HIGH" | "LOW" | "NONE" | "NOT_DEFINED";
  modifiedUserInteraction?: "NONE" | "REQUIRED" | "NOT_DEFINED";
  modifiedScope?: "UNCHANGED" | "CHANGED" | "NOT_DEFINED";
  modifiedConfidentialityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedIntegrityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedAvailabilityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  environmentalScore?: number;
  environmentalSeverity?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  [k: string]: unknown;
}
export interface JSONSchemaForCommonVulnerabilityScoringSystemVersion31 {
  /**
   * CVSS Version
   */
  version: "3.1";
  vectorString: string;
  attackVector?: "NETWORK" | "ADJACENT_NETWORK" | "LOCAL" | "PHYSICAL";
  attackComplexity?: "HIGH" | "LOW";
  privilegesRequired?: "HIGH" | "LOW" | "NONE";
  userInteraction?: "NONE" | "REQUIRED";
  scope?: "UNCHANGED" | "CHANGED";
  confidentialityImpact?: "NONE" | "LOW" | "HIGH";
  integrityImpact?: "NONE" | "LOW" | "HIGH";
  availabilityImpact?: "NONE" | "LOW" | "HIGH";
  baseScore: number;
  baseSeverity: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  exploitCodeMaturity?: "UNPROVEN" | "PROOF_OF_CONCEPT" | "FUNCTIONAL" | "HIGH" | "NOT_DEFINED";
  remediationLevel?: "OFFICIAL_FIX" | "TEMPORARY_FIX" | "WORKAROUND" | "UNAVAILABLE" | "NOT_DEFINED";
  reportConfidence?: "UNKNOWN" | "REASONABLE" | "CONFIRMED" | "NOT_DEFINED";
  temporalScore?: number;
  temporalSeverity?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  confidentialityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  integrityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  availabilityRequirement?: "LOW" | "MEDIUM" | "HIGH" | "NOT_DEFINED";
  modifiedAttackVector?: "NETWORK" | "ADJACENT_NETWORK" | "LOCAL" | "PHYSICAL" | "NOT_DEFINED";
  modifiedAttackComplexity?: "HIGH" | "LOW" | "NOT_DEFINED";
  modifiedPrivilegesRequired?: "HIGH" | "LOW" | "NONE" | "NOT_DEFINED";
  modifiedUserInteraction?: "NONE" | "REQUIRED" | "NOT_DEFINED";
  modifiedScope?: "UNCHANGED" | "CHANGED" | "NOT_DEFINED";
  modifiedConfidentialityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedIntegrityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  modifiedAvailabilityImpact?: "NONE" | "LOW" | "HIGH" | "NOT_DEFINED";
  environmentalScore?: number;
  environmentalSeverity?: "NONE" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  [k: string]: unknown;
}
/**
 * Contains the EPSS data.
 */
export interface EPSS {
  percentile: Percentile;
  probability: Probability;
  timestamp: EPSSTimestamp;
}
/**
 * This schema defines the structure to represent an SSVC SelectionList object.
 */
export interface SSVCv2 {
  timestamp: Timestamp;
  schemaVersion: Schemaversion;
  target_ids?: TargetIds;
  selections: Selections;
  decision_point_resources?: DecisionPointResources;
  references?: References;
}
/**
 * A minimal selection object that contains the decision point ID and the selected values.
 * While the Selection object parallels the DecisionPoint object, it is intentionally minimal, with
 * fewer required fields and no additional metadata, as it is meant to represent a selection made from a
 * previously defined decision point. The expectation is that a Selection object will usually have
 * fewer values than the original decision point, as it represents a specific evaluation
 * at a specific time and may therefore rule out some values that were previously considered.
 * Other fields like name and description may be copied from the decision point, but are not required.
 */
export interface Selection {
  namespace: Namespace;
  key: Key;
  version: Version1;
  name?: Name;
  definition?: Definition;
  values: Values;
}
/**
 * A minimal representation of a decision point value.
 * Intended to parallel the DecisionPointValue object, but with fewer required fields.
 * A decision point value is uniquely identified within a decision point by its key.
 * Globally, the combination of Decision Point namespace, key, and version coupled with the value key
 * uniquely identifies a value across all decision points and values.
 * Other required fields in the DecisionPointValue object, such as name and description, are optional here.
 */
export interface MinimalDecisionPointValue {
  name?: Name1;
  definition?: Definition1;
  key: Key1;
}
/**
 * A reference to a resource that provides additional context about the decision points or selections.
 * This object is intentionally minimal and contains only the URL and an optional description.
 */
export interface Reference1 {
  uri: Uri;
  summary: Summary;
}
/**
 * Contains different lists of product_ids which provide details on the status of the referenced product related to the current vulnerability.
 */
export interface ProductStatus {
  first_affected?: ListOfProductIds1;
  first_fixed?: ListOfProductIds2;
  fixed?: ListOfProductIds3;
  known_affected?: ListOfProductIds4;
  known_not_affected?: ListOfProductIds5;
  last_affected?: ListOfProductIds6;
  recommended?: ListOfProductIds7;
  under_investigation?: ListOfProductIds8;
  unknown?: ListOfProductIds9;
}
/**
 * Specifies details on how to handle (and presumably, fix) a vulnerability.
 */
export interface Remediation {
  category: CategoryOfTheRemediation;
  date?: DateOfTheRemediation;
  details: DetailsOfTheRemediation;
  entitlements?: ListOfEntitlements;
  group_ids?: ListOfProductGroupIds;
  product_ids?: ListOfProductIds;
  restart_required?: RestartRequiredByRemediation;
  url?: URLToTheRemediation;
}
/**
 * Provides information on the category of restart required by this remediation to become effective.
 */
export interface RestartRequiredByRemediation {
  category: CategoryOfRestart;
  details?: AdditionalRestartInformation;
}
/**
 * Contains the vulnerability kinetic information. This information can change as the vulnerability ages and new information becomes available.
 */
export interface Threat {
  category: CategoryOfTheThreat;
  date?: DateOfTheThreat;
  details: DetailsOfTheThreat;
  group_ids?: ListOfProductGroupIds;
  product_ids?: ListOfProductIds;
}
