basePath: /api
definitions:
  config.FeedLogLevel:
    enum:
    - 1
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - defaultSourcesFeedLogLevel
    - DebugFeedLogLevel
    - InfoFeedLogLevel
    - WarnFeedLogLevel
    - ErrorFeedLogLevel
  models.Error:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  models.ID:
    properties:
      id:
        type: integer
    type: object
  models.Success:
    properties:
      message:
        type: string
    type: object
  sources.Stats:
    properties:
      downloading:
        type: integer
      waiting:
        type: integer
    type: object
  time.Duration:
    enum:
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    type: integer
    x-enum-varnames:
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
  web.attentionSources.attention:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  web.defaultSourceConfig.sourceConfig:
    properties:
      age:
        $ref: '#/definitions/web.sourceAge'
      log_level:
        $ref: '#/definitions/config.FeedLogLevel'
      rate:
        type: number
      secure:
        type: boolean
      signature_check:
        type: boolean
      slots:
        type: integer
      strict_mode:
        type: boolean
    type: object
  web.feed:
    properties:
      id:
        type: integer
      label:
        type: string
      log_level:
        $ref: '#/definitions/config.FeedLogLevel'
      rolie:
        type: boolean
      stats:
        $ref: '#/definitions/sources.Stats'
      url:
        type: string
    type: object
  web.feedLogs.entry:
    properties:
      feed_id:
        type: integer
      level:
        $ref: '#/definitions/config.FeedLogLevel'
      msg:
        type: string
      time:
        type: string
    type: object
  web.feedLogs.feedLogEntries:
    properties:
      count:
        type: integer
      entries:
        items:
          $ref: '#/definitions/web.feedLogs.entry'
        type: array
    type: object
  web.feedResult:
    properties:
      feeds:
        items:
          $ref: '#/definitions/web.feed'
        type: array
    type: object
  web.keepFeedTime.keepFeedTimeConfig:
    properties:
      keep_feed_time:
        $ref: '#/definitions/time.Duration'
    type: object
  web.sourceAge:
    properties:
      time.Duration:
        enum:
        - 1
        - 1000
        - 1000000
        - 1000000000
        - 60000000000
        - 1
        - 1000
        - 1000000
        - 1000000000
        - 60000000000
        - 3600000000000
        type: integer
        x-enum-varnames:
        - Nanosecond
        - Microsecond
        - Millisecond
        - Second
        - Minute
        - Nanosecond
        - Microsecond
        - Millisecond
        - Second
        - Minute
        - Hour
    type: object
info:
  contact:
    email: info@intevation.de
    name: ISDuBA team
    url: https://github.com/ISDuBA/ISDuBA
  description: This is the ISDuBA API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ISDuBA API
  version: "1.0"
paths:
  /documents:
    post:
      consumes:
      - application/json
      description: Upload endpoint for CSAF documents.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "403":
          description: False TLP or publisher
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: Already in database
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Imports a CSAF document.
  /documents/{id}:
    delete:
      description: Delete endpoint for CSAF documents.
      parameters:
      - description: Document ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Deletes a CSAF document.
  /sources/{id}:
    delete:
      description: Deletes the source configuration with the specified id.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: source deleted
          schema:
            $ref: '#/definitions/models.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Deletes a source.
    get:
      description: Returns the source configuration and metadata.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enable statistic
        in: query
        name: stats
        type: boolean
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Success'
        "400":
          description: could not parse stats
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
      summary: Get source information.
    put:
      description: Updates the source configuration.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Updates source configuration.
  /sources/{id}/feeds:
    get:
      description: Returns all feed configurations and metadata.
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enable statistic
        in: query
        name: stats
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.feedResult'
        "400":
          description: could not parse stats
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Returns feeds.
    post:
      description: Creates a feed with the specified configuration.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enable statistic
        in: query
        name: stats
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ID'
            type: array
        "400":
          description: could not parse stats
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Creates a feed.
  /sources/attention:
    get:
      description: All sources that had a change and should be reviewed are returned.
      parameters:
      - description: Return all sources
        in: query
        name: all
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/web.attentionSources.attention'
            type: array
        "400":
          description: could not parse all
          schema:
            $ref: '#/definitions/models.Error'
      summary: Returns a list of sources that need attention.
  /sources/default:
    get:
      description: Returns the default parameters for the source configuration.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.defaultSourceConfig.sourceConfig'
      summary: Returns the default configuration.
  /sources/feeds/{id}:
    put:
      description: Updates a feed with the specified configuration.
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Updates a feed.
  /sources/feeds/{id}/log:
    get:
      description: Updates a feed with the specified configuration.
      parameters:
      - description: Feed ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.feedLogs.feedLogEntries'
        "400":
          description: could not parse id
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Updates a feed.
  /sources/feeds/keep:
    get:
      description: Returns the time it takes until old feed entries are deleted.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.keepFeedTime.keepFeedTimeConfig'
      summary: Returns how long feed logs are kept.
  /sources/feeds/log:
    get:
      description: Updates a feed with the specified configuration.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.feedLogs.feedLogEntries'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Updates a feed.
swagger: "2.0"
