basePath: /api
definitions:
  models.AdvisoryKey:
    properties:
      publisher:
        type: string
      tracking_id:
        type: string
    required:
    - publisher
    - tracking_id
    type: object
  results.Error:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  results.ID:
    properties:
      id:
        type: integer
    type: object
  results.Success:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: info@intevation.de
    name: ISDuBA team
    url: https://github.com/ISDuBA/ISDuBA
  description: This is the ISDuBA API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ISDuBA API
  version: "1.0"
paths:
  /documents:
    post:
      consumes:
      - application/json
      description: Upload endpoint for CSAF documents.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/results.ID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/results.Error'
        "403":
          description: False TLP or publisher
          schema:
            $ref: '#/definitions/results.Error'
        "409":
          description: Already in database
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Imports a CSAF document.
  /documents/{id}:
    delete:
      description: Delete endpoint for CSAF documents.
      parameters:
      - description: Document ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/results.ID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/results.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Deletes a CSAF document.
  /sources/{id}:
    delete:
      description: Deletes the source configuration with the specified id.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: source deleted
          schema:
            $ref: '#/definitions/results.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/results.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Deletes a source.
    get:
      description: Returns the source configuration and metadata.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enable statistic
        in: query
        name: stats
        type: boolean
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/results.Success'
        "400":
          description: could not parse stats
          schema:
            $ref: '#/definitions/results.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/results.Error'
      summary: Get source information.
    put:
      consumes:
      - application/json
      description: Updates the source configuration.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/results.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/results.Error'
        "404":
          description: not found
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Update source configuration.
  /sources/{id}/feeds:
    get:
      consumes:
      - application/json
      description: Returns all feed configurations and metadata.
      parameters:
      - description: Source ID
        in: path
        name: id
        required: true
        type: integer
      - description: Enable statistic
        in: query
        name: stats
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.AdvisoryKey'
            type: array
        "400":
          description: could not parse stats
          schema:
            $ref: '#/definitions/results.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Returns feeds.
swagger: "2.0"
