basePath: /api
definitions:
  results.Error:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  results.ID:
    properties:
      id:
        type: integer
    type: object
info:
  contact:
    email: info@intevation.de
    name: ISDuBA team
    url: https://github.com/ISDuBA/ISDuBA
  description: This is the ISDuBA API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ISDuBA API
  version: "1.0"
paths:
  /documents:
    post:
      consumes:
      - application/json
      description: Upload endpoint for CSAF documents.
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/results.ID'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/results.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/results.Error'
      summary: Imports a CSAF document.
swagger: "2.0"
