-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2024 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
-- Software-Engineering: 2024 Intevation GmbH <https://intevation.de>

CREATE TABLE IF NOT EXISTS jobs (
    id                      int       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                    varchar   NOT NULL,
    insecure                bool      NOT NULL DEFAULT FALSE,
    ignore_signature_check  bool      NOT NULL DEFAULT FALSE,
    client_certs            bytea[],
    client_key              varchar,
    client_passphrase       varchar,
    rate                    float,
    worker                  int       NOT NULL DEFAULT 1,
    start_range             timestamp with time zone,
    end_range               timestamp with time zone,
    ignore_pattern          varchar,
    temporary               bool      NOT NULL DEFAULT FALSE,

    domains                 varchar[] NOT NULL,

    UNIQUE (name)
);

CREATE TYPE status_type AS ENUM(
    'QUEUED', 'RUNNING', 'FAILED', 'COMPLETED');

CREATE TABLE IF NOT EXISTS tasks (
    id                      int       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created                 timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    job_id                  int       NOT NULL REFERENCES jobs(id),
    status                  status_type
);

CREATE TABLE IF NOT EXISTS cron (
    id                      int       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                    varchar   NOT NULL,
    job_id                  int       REFERENCES jobs(id),
    cron_timing             varchar   NOT NULL,

    UNIQUE (name)
);

--
-- permissions
--
GRANT INSERT, DELETE, SELECT, UPDATE ON jobs TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON tasks TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON cron TO {{ .User | sanitize }};
