-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2024 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
-- Software-Engineering: 2024 Intevation GmbH <https://intevation.de>

CREATE TABLE IF NOT EXISTS job_config (
    id                      int       PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                    varchar   NOT NULL,
    insecure                bool      NOT NULL DEFAULT FALSE,
    ignore_signature_check  bool      NOT NULL DEFAULT FALSE,
    client_certs            bytea[],
    client_key              varchar,
    client_passphrase       varchar,
    rate                    float,
    worker                  int       NOT NULL DEFAULT 1,
    start_range             timestamp with time zone,
    end_range               timestamp with time zone,
    ignore_pattern          varchar,

    domains                 varchar[] NOT NULL,

    UNIQUE (name)
);

