-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2024 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
-- Software-Engineering: 2024 Intevation GmbH <https://intevation.de>

CREATE TABLE sources (
    id     int     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name   varchar NOT NULL UNIQUE,
    domain varchar,
    pmd    varchar,
    active bool NOT NULL DEFAULT false,
    rate   float,
    slots  int,
    CHECK(name <> ''),
    CHECK(domain <> ''),
    CHECK((domain IS NOT NULL AND pmd IS NULL) OR (domain IS NULL AND pmd IS NOT NULL)),
    CHECK(rate IS NULL OR rate > 0.0),
    CHECK(slots IS NULL OR slots >= 1)
);

CREATE TABLE feeds (
    id         int     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    label      varchar NOT NULL,
    sources_id int     NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
    url        varchar NOT NULL,
    rolie      bool    NOT NULL DEFAULT false,
    CHECK(label <> ''),
    CHECK(url <> ''),
    UNIQUE(label, sources_id)
);

CREATE TABLE changes (
    url      varchar     NOT NULL,
    time     timestamptz NOT NULL,
    feeds_id int         NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
    PRIMARY KEY(url, feeds_id),
    CHECK(url <> '')
);

CREATE TYPE feed_logs_level AS ENUM (
    'info', 'debug', 'warn', 'error');

CREATE TABLE feed_logs (
    feeds_id int             NOT NULL REFERENCES feeds(id) ON DELETE CASCADE,
    lvl      feed_logs_level NOT NULL DEFAULT 'info',
    time     timestamptz     NOT NULL,
    msg      text            NOT NULL
);

CREATE INDEX ON feed_logs(time);

GRANT INSERT, DELETE, SELECT, UPDATE ON sources   TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON feeds     TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON changes   TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON feed_logs TO {{ .User | sanitize }};
