-- This file is Free Software under the Apache-2.0 License
-- without warranty, see README.md and LICENSES/Apache-2.0.txt for details.
--
-- SPDX-License-Identifier: Apache-2.0
--
-- SPDX-FileCopyrightText: 2025 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
-- Software-Engineering: 2025 Intevation GmbH <https://intevation.de>

CREATE TABLE forwarders (
    id  int     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url varchar NOT NULL UNIQUE
);

CREATE TYPE forward_state AS ENUM (
    'pending', 'uploaded', 'failed');

CREATE TABLE forwarders_queue (
    forwarders_id int           NOT NULL REFERENCES forwarders(id) ON DELETE CASCADE,
    documents_id  int           NOT NULL REFERENCES documents(id)  ON DELETE CASCADE,
    state         forward_state NOT NULL DEFAULT 'pending',
    PRIMARY KEY(forwarders_id, documents_id)
);

INSERT INTO forwarders (url) SELECT DISTINCT(url) FROM forwarded_documents;

INSERT INTO forwarders_queue (forwarders_id, documents_id, state)
    SELECT
        fw.id,
        fwd.documents_id,
        'uploaded'
    FROM forwarded_documents fwd JOIN forwarders fw ON fwd.url = fw.url;

DROP TABLE forwarded_documents;

CREATE INDEX ON forwarders_queue(state) WHERE state <> 'uploaded';

GRANT INSERT, DELETE, SELECT, UPDATE ON forwarders       TO {{ .User | sanitize }};
GRANT INSERT, DELETE, SELECT, UPDATE ON forwarders_queue TO {{ .User | sanitize }};
